name: jianpian_linux
description: "荐片 Linux 客户端"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.0
  cached_network_image: ^3.3.0
  crypto: ^3.0.6
  media_kit: ^1.2.6
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
